substitutions:
  # Define any subtitution variables if needed
  _ARTIFACT_REGISTRY_HOSTNAME: 'asia-southeast2-docker.pkg.dev' # Replace with your Artifact Registry hostname
  _GKE_CLUSTER_NAME: 'my-sample-gke-cluster'  # Replace with your GKE cluster name
  _GKE_CLUSTER_ZONE: 'asia-southeast2-a'        # Replace with your GKE cluster zone
  _PROJECT_ID: 'our-hull-385315'              # Replace with your GCP Project ID
  _ARTIFACT_REGISTRY_REPO: 'my-sample-react-app-repo'  # Replace with your Artifact Registry repository name
  _REGION: 'asia-southeast2'               # Replace with your Artifact Registry region
  _APP_NAME: 'my-sample-react-app'                # Replace with your Application name
  _PROJECT_DIR: 'my-sample-react-app' # Replace with your project directory if needed

steps:
  # - name: 'gcr.io/kaniko-project/executor:latest' #For caching building image, using kaniko project
  #   id: Build-Push
  #   dir: '${_PROJECT_DIR}'
  #   args:
  #     - '--destination=${_ARTIFACT_REGISTRY_HOSTNAME}/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_APP_NAME}:$SHORT_SHA'
  #     - '--dockerfile=Containerfile'
  #     - '--cache=true'
  #     - '--context=dir://.'
  # 1. Build Image using tag commit
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    dir: '${_PROJECT_DIR}'
    args:
      - 'build'
      - '-t'
      - '${_ARTIFACT_REGISTRY_HOSTNAME}/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_APP_NAME}:$SHORT_SHA'
      - '-f'
      - 'Containerfile'
      - '.'

  # 2. Push Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - '${_ARTIFACT_REGISTRY_HOSTNAME}/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_APP_NAME}:$SHORT_SHA'

images:
  - '${_ARTIFACT_REGISTRY_HOSTNAME}/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_APP_NAME}:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY