# --- Stage 1: Build ---
# Using FQDN (Full Qualified Domain Name) for better reliability & prevent ambigous
FROM docker.io/library/node:22.21-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

# --- Stage 2: Production ---
FROM docker.io/library/nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]